"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 19:00:20.289329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_login_attempts_ip_at', ['ip', 'attempted_at'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media')),
    sa.UniqueConstraint('slug', name=op.f('uq_media_slug'))
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('exclude_keywords', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('slug', name=op.f('uq_topics_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('manual_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_manual_reviews_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_reviews'))
    )
    with op.batch_alter_table('manual_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_manual_reviews_target', ['target_type', 'target_id'], unique=False)

    op.create_table('story_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_story_groups_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_groups'))
    )
    op.create_table('subsources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('min_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('etag', sa.String(length=256), nullable=True),
    sa.Column('last_modified_header', sa.String(length=128), nullable=True),
    sa.Column('last_fetch_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_subsources_media_id_media'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subsources')),
    sa.UniqueConstraint('media_id', 'url', name=op.f('uq_subsources_media_id'))
    )
    with op.batch_alter_table('subsources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subsources_media_id'), ['media_id'], unique=False)

    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('subsource_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=512), nullable=True),
    sa.Column('section', sa.String(length=256), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('published_precision', sa.String(length=16), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.Date(), nullable=True),
    sa.Column('modified_precision', sa.String(length=16), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('discovery_method', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('extraction_status', sa.String(length=16), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_articles_media_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsource_id'], ['subsources.id'], name=op.f('fk_articles_subsource_id_subsources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('media_id', 'canonical_url', name=op.f('uq_articles_media_id'))
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('ix_articles_first_seen_at', ['first_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_media_id'), ['media_id'], unique=False)
        batch_op.create_index('ix_articles_published_at', ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_subsource_id'), ['subsource_id'], unique=False)

    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subsource_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['subsource_id'], ['subsources.id'], name=op.f('fk_collection_runs_subsource_id_subsources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_runs'))
    )
    with op.batch_alter_table('collection_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_runs_subsource_id'), ['subsource_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_alerts_article_id_articles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['story_groups.id'], name=op.f('fk_alerts_group_id_story_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_alerts_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)

    op.create_table('article_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_a_id', sa.Integer(), nullable=False),
    sa.Column('article_b_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_a_id'], ['articles.id'], name=op.f('fk_article_relations_article_a_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['article_b_id'], ['articles.id'], name=op.f('fk_article_relations_article_b_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_relations')),
    sa.UniqueConstraint('article_a_id', 'article_b_id', 'relation_type', name=op.f('uq_article_relations_article_a_id'))
    )
    with op.batch_alter_table('article_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_relations_article_a_id'), ['article_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_relations_article_b_id'), ['article_b_id'], unique=False)

    op.create_table('headline_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('collection_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_headline_versions_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_run_id'], ['collection_runs.id'], name=op.f('fk_headline_versions_collection_run_id_collection_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_headline_versions'))
    )
    with op.batch_alter_table('headline_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_headline_versions_article_id'), ['article_id'], unique=False)

    op.create_table('story_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('added_by', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_story_group_members_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['story_groups.id'], name=op.f('fk_story_group_members_group_id_story_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_group_members')),
    sa.UniqueConstraint('group_id', 'article_id', name=op.f('uq_story_group_members_group_id'))
    )
    with op.batch_alter_table('story_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_group_members_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_group_members_group_id'), ['group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_group_members_group_id'))
        batch_op.drop_index(batch_op.f('ix_story_group_members_article_id'))

    op.drop_table('story_group_members')
    with op.batch_alter_table('headline_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_headline_versions_article_id'))

    op.drop_table('headline_versions')
    with op.batch_alter_table('article_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_relations_article_b_id'))
        batch_op.drop_index(batch_op.f('ix_article_relations_article_a_id'))

    op.drop_table('article_relations')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    with op.batch_alter_table('collection_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_runs_subsource_id'))
        batch_op.drop_index(batch_op.f('ix_collection_runs_started_at'))

    op.drop_table('collection_runs')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_subsource_id'))
        batch_op.drop_index('ix_articles_published_at')
        batch_op.drop_index(batch_op.f('ix_articles_media_id'))
        batch_op.drop_index(batch_op.f('ix_articles_is_demo'))
        batch_op.drop_index('ix_articles_first_seen_at')

    op.drop_table('articles')
    with op.batch_alter_table('subsources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subsources_media_id'))

    op.drop_table('subsources')
    op.drop_table('story_groups')
    with op.batch_alter_table('manual_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_manual_reviews_target')

    op.drop_table('manual_reviews')
    op.drop_table('users')
    op.drop_table('topics')
    op.drop_table('media')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_login_attempts_ip_at')

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
