"""recoleccion de tres medios

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-04 19:14:47.662831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('article_sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('subsource_id', sa.Integer(), nullable=False),
    sa.Column('item_url', sa.String(length=2048), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_sightings_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsource_id'], ['subsources.id'], name=op.f('fk_article_sightings_subsource_id_subsources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_sightings')),
    sa.UniqueConstraint('article_id', 'subsource_id', name=op.f('uq_article_sightings_article_id'))
    )
    with op.batch_alter_table('article_sightings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_sightings_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_sightings_subsource_id'), ['subsource_id'], unique=False)

    op.create_table('media_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('referenced_media', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_media_references_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_references')),
    sa.UniqueConstraint('article_id', 'referenced_media', 'kind', 'evidence', name=op.f('uq_media_references_article_id'))
    )
    with op.batch_alter_table('media_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_references_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_references_referenced_media'), ['referenced_media'], unique=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('final_url', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('origin_label', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_syndicated', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('body_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('enriched_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('enrich_attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('enrich_error', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_articles_origin_label'), ['origin_label'], unique=False)
        batch_op.create_index('uq_articles_media_source_id', ['media_id', 'source_id'], unique=True, sqlite_where=sa.text('source_id IS NOT NULL'))

    with op.batch_alter_table('collection_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('run_type', sa.String(length=16), server_default='feed', nullable=False))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('items_skipped', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_collection_runs_media_id_media'), 'media', ['media_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('headline_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=16), server_default='feed', nullable=False))

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_domains', sa.Text(), server_default='', nullable=False))

    with op.batch_alter_table('subsources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.String(length=64), server_default='general', nullable=False))
        batch_op.add_column(sa.Column('max_items', sa.Integer(), server_default='300', nullable=False))
        batch_op.add_column(sa.Column('last_status', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('last_http_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_items_found', sa.Integer(), nullable=True))

    # ### end Alembic commands ###
    # Procedencia de los artículos ya existentes: la subfuente que los descubrió.
    op.execute(
        "INSERT INTO article_sightings (article_id, subsource_id, item_url, source_id, "
        "first_seen_at, last_seen_at, times_seen) "
        "SELECT id, subsource_id, url, NULL, first_seen_at, last_seen_at, 1 "
        "FROM articles WHERE subsource_id IS NOT NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subsources', schema=None) as batch_op:
        batch_op.drop_column('last_items_found')
        batch_op.drop_column('last_http_status')
        batch_op.drop_column('last_status')
        batch_op.drop_column('max_items')
        batch_op.drop_column('section')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('allowed_domains')

    with op.batch_alter_table('headline_versions', schema=None) as batch_op:
        batch_op.drop_column('origin')

    with op.batch_alter_table('collection_runs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_collection_runs_media_id_media'), type_='foreignkey')
        batch_op.drop_column('items_skipped')
        batch_op.drop_column('attempts')
        batch_op.drop_column('run_type')
        batch_op.drop_column('media_id')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('uq_articles_media_source_id', sqlite_where=sa.text('source_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_articles_origin_label'))
        batch_op.drop_column('enrich_error')
        batch_op.drop_column('enrich_attempts')
        batch_op.drop_column('enriched_at')
        batch_op.drop_column('body_text')
        batch_op.drop_column('is_syndicated')
        batch_op.drop_column('origin_label')
        batch_op.drop_column('final_url')
        batch_op.drop_column('source_id')

    with op.batch_alter_table('media_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_references_referenced_media'))
        batch_op.drop_index(batch_op.f('ix_media_references_article_id'))

    op.drop_table('media_references')
    with op.batch_alter_table('article_sightings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_sightings_subsource_id'))
        batch_op.drop_index(batch_op.f('ix_article_sightings_article_id'))

    op.drop_table('article_sightings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
