"""relaciones y grupos

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-04 19:37:32.583926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_relations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scores', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('algorithm_version', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('time_delta_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_note', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('review_status', sa.String(length=16), server_default='pendiente', nullable=False))
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_article_relations_review_status'), ['review_status'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_article_relations_reviewed_by_id_users'), 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('story_group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=16), server_default='activo', nullable=False))
        batch_op.add_column(sa.Column('centrality', sa.Float(), nullable=True))

    with op.batch_alter_table('story_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('merged_into_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('article_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('media_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('independent_media_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('common_terms', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('first_seen_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('algorithm_version', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_story_groups_merged_into_id_story_groups'), 'story_groups', ['merged_into_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_story_groups_merged_into_id_story_groups'), type_='foreignkey')
        batch_op.drop_column('algorithm_version')
        batch_op.drop_column('first_seen_at')
        batch_op.drop_column('explanation')
        batch_op.drop_column('common_terms')
        batch_op.drop_column('independent_media_count')
        batch_op.drop_column('media_count')
        batch_op.drop_column('article_count')
        batch_op.drop_column('merged_into_id')
        batch_op.drop_column('locked')

    with op.batch_alter_table('story_group_members', schema=None) as batch_op:
        batch_op.drop_column('centrality')
        batch_op.drop_column('status')

    with op.batch_alter_table('article_relations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_article_relations_reviewed_by_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_article_relations_review_status'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('review_note')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_id')
        batch_op.drop_column('review_status')
        batch_op.drop_column('time_note')
        batch_op.drop_column('time_delta_seconds')
        batch_op.drop_column('algorithm_version')
        batch_op.drop_column('rules')
        batch_op.drop_column('scores')

    # ### end Alembic commands ###
