"""alertas y notificaciones

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-04 19:57:55.243360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_events_alert_id_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alert_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_events'))
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_events_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_created_at'), ['created_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_notifications_alert_id_alerts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_notifications_dedupe_key'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=8), server_default='baja', nullable=False))
        batch_op.add_column(sa.Column('priority_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('article_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('media_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('independent_media_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('fingerprint', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('common_source', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('limitations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_material_change_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_notified_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_alerts_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index('uq_alerts_group_id', ['group_id'], unique=True, sqlite_where=sa.text('group_id IS NOT NULL'))
        batch_op.create_foreign_key(batch_op.f('fk_alerts_reviewed_by_id_users'), 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_alerts_reviewed_by_id_users'), type_='foreignkey')
        batch_op.drop_index('uq_alerts_group_id', sqlite_where=sa.text('group_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_priority'))
        batch_op.drop_column('last_notified_at')
        batch_op.drop_column('last_material_change_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('review_note')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_id')
        batch_op.drop_column('limitations')
        batch_op.drop_column('common_source')
        batch_op.drop_column('version')
        batch_op.drop_column('fingerprint')
        batch_op.drop_column('independent_media_count')
        batch_op.drop_column('media_count')
        batch_op.drop_column('article_count')
        batch_op.drop_column('priority_reason')
        batch_op.drop_column('priority')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_alert_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_alert_events_alert_id'))

    op.drop_table('alert_events')
    # ### end Alembic commands ###
