"""analisis con ia

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-04 20:17:09.785017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('relation_id', sa.Integer(), nullable=True),
    sa.Column('article_a_id', sa.Integer(), nullable=False),
    sa.Column('article_b_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('flags', sa.Text(), nullable=True),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('input_chars', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_a_id'], ['articles.id'], name=op.f('fk_ai_analyses_article_a_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['article_b_id'], ['articles.id'], name=op.f('fk_ai_analyses_article_b_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relation_id'], ['article_relations.id'], name=op.f('fk_ai_analyses_relation_id_article_relations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses'))
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analyses_article_a_id'), ['article_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_article_b_id'), ['article_b_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_cache_key'), ['cache_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_relation_id'), ['relation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_status'), ['status'], unique=False)

    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], name=op.f('fk_ai_usage_analysis_id_ai_analyses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage'))
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_day'), ['day'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_day'))

    op.drop_table('ai_usage')
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_relation_id'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_cache_key'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_article_b_id'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_article_a_id'))

    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
