"""bloqueos de ejecucion

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-05 01:07:08.696556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_locks',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_job_locks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_locks')
    # ### end Alembic commands ###
